name: Scheduled security audit
on:
  schedule:
    #run at hour 0 minute 0 every first day of the week of every month of every year
    - cron: '0 0 0 * *'

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run audit
        uses: actions-rs/audit-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
